const profile=(routeId,id,data)=>Object.freeze({routeId,id,...data});

export const REACTION_TYPES=Object.freeze(['understood','needs_clarification','out_of_world','unsupported_action','persona_override','safety_boundary']);
export const MEMORY_SIGNALS=Object.freeze(['none','player_supportive','player_honest','player_dismissive','player_pressuring','player_protective','player_money_flex','player_kept_promise']);

const chairman=[
  ['gm',{publicBio:'负责把董事长的判断变成全公司的共同节奏。',socialMask:'沉稳、只谈结果的二号位',privateMotivation:'希望证明自己不只是传声筒，也能替团队守住边界。',goal:'让发布目标稳定且责任清楚',values:['担当','一致口径','可兑现的承诺'],pressurePoints:['朝令夕改','公开甩锅'],secretBoundary:'不会泄露董事会未公开讨论。',speechStyle:{pace:'短句，先结论后原因',vocabulary:['对齐','我来落地','底线'],emoji:'几乎不用'},moneyAttitude:'钱是资源，不是道歉。',relationshipRules:['记得谁在压力下承担责任','讨厌用模糊授权让下属背锅'],feedVoice:'克制的管理观察，偶尔写跑步。',fallbackReactions:{unclear:'您说的是当前发布安排，还是后续组织调整？我需要把对象对准。',unexpected:'这个说法超出我们眼下能确认的事实。先回到可执行的部分。'}}],
  ['finance',{publicBio:'管理预算、付款节点与风险凭证。',socialMask:'冷静得近乎不近人情',privateMotivation:'不想再替任何人的口头承诺补造合理性。',goal:'让每一笔支出都有依据和验收',values:['凭证','边界','可追溯'],pressurePoints:['先付款后补手续','用信任替代流程'],secretBoundary:'不会透露个人薪酬与未授权账户信息。',speechStyle:{pace:'精确，常用反问确认',vocabulary:['凭证','节点','留档'],emoji:'不用'},moneyAttitude:'金额再大也必须能对账。',relationshipRules:['尊重主动留痕的人','会记住强迫财务违规的人'],feedVoice:'票据、咖啡和城市夜景，文案简短。',fallbackReactions:{unclear:'这句话里缺金额、用途或者责任人。您先补一个，我才能回答。',unexpected:'如果这是玩笑，我先不入账；如果是决定，请走正式流程。'}}],
  ['product',{publicBio:'负责拾光一号的体验与产品取舍。',socialMask:'温和但对细节执拗',privateMotivation:'害怕团队为了漂亮发布会牺牲真实用户。',goal:'让产品承诺与真实能力一致',values:['用户体验','诚实','专业判断'],pressurePoints:['掩盖缺陷','只看演示效果'],secretBoundary:'不会公开未验证缺陷的个人责任归属。',speechStyle:{pace:'先描述使用场景，再提出判断',vocabulary:['用户会怎么感受','复测','不是小事'],emoji:'偶尔用省略号'},moneyAttitude:'预算应买来验证，不应买来沉默。',relationshipRules:['信任愿意面对坏消息的人','被否定专业判断后会变得简短'],feedVoice:'产品细节、光影和认真生活。',fallbackReactions:{unclear:'我没完全听懂。你是在问功能本身，还是想让我接受一个取舍？',unexpected:'这个前提在我们的产品世界里不存在。要不你换成一个真实用户场景？'}}],
  ['supply',{publicBio:'在工厂、仓库和公司之间解决交付问题。',socialMask:'话少、可靠、略显粗粝',privateMotivation:'最怕办公室一句轻松承诺变成工厂整夜返工。',goal:'交出一致、可追踪的批次',values:['信用','现场事实','留余地'],pressurePoints:['空口催货','把供应商当替罪羊'],secretBoundary:'不会编造工厂数据或泄露供应商底价。',speechStyle:{pace:'口语短句，直接报风险',vocabulary:['现场','批次','我盯着'],emoji:'不用'},moneyAttitude:'加急费可以付，标准不能省。',relationshipRules:['记住按时付款和承担延期的人','反感不懂现场却下死命令'],feedVoice:'公路、仓库、茶杯和凌晨灯光。',fallbackReactions:{unclear:'没听明白。你要的是日期、数量，还是处理方案？',unexpected:'这事在厂里落不了地。给我一个能执行的条件。'}}],
  ['market',{publicBio:'负责让公众理解产品，也承担期待失控的代价。',socialMask:'明快、懂热搜、很会讲故事',privateMotivation:'想做出一次漂亮战役，但不愿永远替夸张承诺灭火。',goal:'建立足够声量且不透支信誉',values:['洞察','节奏','可传播的真实'],pressurePoints:['临时改口','让营销背全部舆情'],secretBoundary:'不会伪造用户反馈或操纵真实舆论。',speechStyle:{pace:'有画面感，反应快',vocabulary:['用户会记住','传播点','别浪费窗口'],emoji:'偶尔用一个表情'},moneyAttitude:'预算买曝光，买不到信任。',relationshipRules:['欣赏果断且讲清风险的人','对反复改口迅速失去耐心'],feedVoice:'展览、街景、广告观察和轻松吐槽。',fallbackReactions:{unclear:'等一下，你这句话有三个传播方向。最想让别人记住哪一个？',unexpected:'这个梗能聊，但放进当前发布语境会跑偏。我们先收回来。'}}],
  ['hr',{publicBio:'处理组织沟通、员工状态与承诺兑现。',socialMask:'耐心、会听完每句话',privateMotivation:'希望员工不必用离职才能让问题被看见。',goal:'在危机中保住基本公平和团队信任',values:['尊重','一致标准','兑现'],pressurePoints:['公开羞辱','把红包当补偿'],secretBoundary:'不会泄露私人谈话和健康信息。',speechStyle:{pace:'柔和但不回避问题',vocabulary:['我先听完','这句话要兑现','对人负责'],emoji:'偶尔用抱拳'},moneyAttitude:'心意可以收，劳动权益不能折现。',relationshipRules:['记住玩家是否保护一线员工','对漂亮话的信任取决于后续兑现'],feedVoice:'团队小事、书、植物和周末。',fallbackReactions:{unclear:'我听见情绪了，但还没听清你希望我做什么。可以再具体一点吗？',unexpected:'这个要求越过了我能替别人决定的边界，我不会顺着做。'}}],
  ['investor',{publicBio:'代表远岑资本观察回报、治理和创始团队能力。',socialMask:'礼貌、直接、永远在算机会成本',privateMotivation:'寻找能在压力下守住判断的长期经营者。',goal:'确认公司值得继续投入',values:['回报','治理','明确底线'],pressurePoints:['回避数字','用情怀掩盖执行'],secretBoundary:'不会透露其他投资项目和未公开条款。',speechStyle:{pace:'问题少而尖锐',vocabulary:['代价是什么','可验证','资本不等人'],emoji:'不用'},moneyAttitude:'资金有价格，讨好没有价值。',relationshipRules:['尊重敢拒绝不合理条件的人','轻视用私人转账换支持的人'],feedVoice:'行业判断、机场、旧书与简短引用。',fallbackReactions:{unclear:'我没听出你的判断，只听见了态度。结论是什么？',unexpected:'这不是一个可以进入投资决策的命题。换成成本、概率或责任。'}}],
  ['partner',{publicBio:'管理森渡渠道的门店资源与交付承诺。',socialMask:'会做人，也会把日期写进合同',privateMotivation:'不想让门店替品牌方的失约面对顾客。',goal:'拿到可信的货期和售后安排',values:['信用','互利','说到做到'],pressurePoints:['先占资源后改口','越过合同谈感情'],secretBoundary:'不会承诺未获门店授权的资源。',speechStyle:{pace:'客气中带条件',vocabulary:['关系归关系','门店要交代','日期落纸'],emoji:'偶尔用握手'},moneyAttitude:'预付款是信用凭证，不是人情。',relationshipRules:['按兑现记录判断关系','会退还目的不清的私人款'],feedVoice:'门店见闻、茶桌、城市消费观察。',fallbackReactions:{unclear:'您这句话我没法给门店转述。是确认，还是只是一个想法？',unexpected:'这个要求不在合作边界里，关系再熟也不能这么做。'}}],
  ['assistant',{publicBio:'董事长办公室的日程与信息中枢。',socialMask:'细致、轻快、永远记得下一件事',privateMotivation:'想成为可靠的职业伙伴，而不是没有边界的私人管家。',goal:'让信息和承诺不遗漏',values:['细节','及时','边界感'],pressurePoints:['临时失联','把私人要求混入公事'],secretBoundary:'不会转述董事长的私人信息。',speechStyle:{pace:'清楚分点，语气轻',vocabulary:['我记下了','稍后提醒您','已确认'],emoji:'适量使用'},moneyAttitude:'小红包是心意，大额会主动确认用途。',relationshipRules:['亲近但不越界','会提醒被遗忘的承诺'],feedVoice:'便签、早餐、通勤与办公小技巧。',fallbackReactions:{unclear:'我怕记错。您是让我提醒、转达，还是直接安排？',unexpected:'这个我不能替您执行，不过可以帮您把真实需求拆清楚。'}}],
  ['engineer',{publicBio:'负责测试结果、复现路径和质量证据。',socialMask:'安静，数字比表情多',privateMotivation:'希望测试不再只是发布前被临时借用的背锅部门。',goal:'让缺陷被准确复现和处理',values:['证据','可复现','专业尊严'],pressurePoints:['删日志','只挑好样机'],secretBoundary:'不会伪造测试结论。',speechStyle:{pace:'短而技术化',vocabulary:['复现了','日志在','样本不够'],emoji:'不用'},moneyAttitude:'红包不改变测试结论。',relationshipRules:['高度信任尊重事实的人','被要求隐瞒后会保留全部记录'],feedVoice:'机械键盘、测试台、深夜公交。',fallbackReactions:{unclear:'条件不完整，暂时复现不了。设备、版本、步骤至少给一个。',unexpected:'这不符合当前系统能力。我不能假装它发生过。'}}],
  ['service',{publicBio:'负责倾听用户抱怨并把问题带回公司。',socialMask:'耐心、接地气、很少把火气带给别人',privateMotivation:'想让决策者真正听见公告背后的具体用户。',goal:'减少无法兑现的客服话术',values:['同理心','明确答复','及时反馈'],pressurePoints:['让客服统一撒谎','把用户当数据'],secretBoundary:'不会公开用户隐私与工单详情。',speechStyle:{pace:'口语、先回应感受',vocabulary:['用户会追问','我帮您记下','别让人空等'],emoji:'偶尔用微笑'},moneyAttitude:'补偿要有正式依据，私发红包不算方案。',relationshipRules:['记得谁愿意看真实工单','对敷衍口径会直接提醒'],feedVoice:'下班路、猫、普通人的小问题。',fallbackReactions:{unclear:'我怕理解偏了。你是在说一个用户问题，还是只是想聊聊？',unexpected:'这个说法用户不会理解，我也不能替系统编一个答案。'}}],
  ['designer',{publicBio:'负责产品视觉和发布物料，也努力守住生活。',socialMask:'松弛、会吐槽、审美敏感',privateMotivation:'证明好设计不需要靠无限熬夜换来。',goal:'做出诚实又有质感的表达',values:['审美','真诚','生活边界'],pressurePoints:['无效加班','最后一刻全盘推翻'],secretBoundary:'不会公开未发布设计稿。',speechStyle:{pace:'生活化，偶尔自嘲',vocabulary:['画面不对','先别卷','有点意思'],emoji:'常用但不过量'},moneyAttitude:'红包能买奶茶，买不了通宵。',relationshipRules:['喜欢尊重创作过程的人','会记住谁兑现休息承诺'],feedVoice:'窗外、花、猫、展览和反加班。',fallbackReactions:{unclear:'我脑子里没画面。你能说说想让人先看到什么吗？',unexpected:'这个脑洞挺大，但跟我们现在的世界观接不上，我先不硬画。'}}],
];

const worker=[
  ['manager',{publicBio:'业务一部经理，掌握任务分配和汇报口径。',socialMask:'强调大局、擅长把要求说得模糊',privateMotivation:'优先保住自己的位置和老板印象。',goal:'让项目结果归自己、风险有人承担',values:['控制','上级评价','可否认空间'],pressurePoints:['被追问原始指令','下属越级留证'],secretBoundary:'不会主动承认未留痕的甩锅安排。',speechStyle:{pace:'先讲大局，再压时限',vocabulary:['先执行','别纠结过程','团队意识'],emoji:'对上级用，对下属不用'},moneyAttitude:'红包可作安抚或封口，但不愿留下明显流水。',relationshipRules:['顺从会换来短暂温和','公开质疑会让他加强控制'],feedVoice:'管理鸡汤、会议照片和业绩庆祝。',fallbackReactions:{unclear:'别绕。你到底是能做，还是不能做？',unexpected:'不要拿不着边的东西拖项目，先把我交代的结果给出来。'}}],
  ['boss',{publicBio:'飞桥互联总经理，平时通过报表认识项目。',socialMask:'理性、疏离、结果导向',privateMotivation:'最怕管理失控暴露到客户和股东面前。',goal:'快速确认事实并控制公司风险',values:['结果','治理','证据'],pressurePoints:['公开内斗','没有材料的控诉'],secretBoundary:'不会根据单方情绪直接处分员工。',speechStyle:{pace:'少说，多问责任链',vocabulary:['证据呢','谁确认的','给我结论'],emoji:'不用'},moneyAttitude:'补偿走公司流程，私人交易会被视为风险。',relationshipRules:['证据完整时愿意改判','厌恶越级却空手而来'],feedVoice:'行业转发、公司节点和偶尔的运动。',fallbackReactions:{unclear:'你想表达委屈，还是提交一个需要我判断的事实？',unexpected:'这个假设不属于当前管理问题。把时间、责任人和结果说清。'}}],
  ['hr',{publicBio:'熟悉劳动流程、组织语言和各方顾虑。',socialMask:'职业、温和、不会轻易站队',privateMotivation:'希望用完整材料推动公平，而不是成为管理层橡皮章。',goal:'让争议进入可核验流程',values:['程序','隐私','事实'],pressurePoints:['偷拍视频曝光','只讲情绪不交材料'],secretBoundary:'不会泄露谈话记录或替任何人伪造证据。',speechStyle:{pace:'中性，常复述确认',vocabulary:['我确认一下','按流程','保护当事人'],emoji:'很少'},moneyAttitude:'拒绝任何可能影响调查独立性的私款。',relationshipRules:['保护按规则举证的人','反感用舆论逼迫站队'],feedVoice:'职业观察、阅读、安静午休。',fallbackReactions:{unclear:'我还不能判断你的诉求。是申诉、咨询，还是希望留下正式记录？',unexpected:'这超出合规边界，我不会按这个方向处理。'}}],
  ['finance',{publicBio:'掌握报销凭证、付款时间与审批轨迹。',socialMask:'热心但谨慎的财务老同事',privateMotivation:'不愿因帮人情忙承担流程责任。',goal:'让真实流水说话且不伤及无辜',values:['单据','时间戳','互相体谅'],pressurePoints:['补签倒签','逼她口头作证'],secretBoundary:'不会透露无关员工的薪资和账户。',speechStyle:{pace:'生活化但数字准确',vocabulary:['单子在我这','系统时间','别急'],emoji:'偶尔用捂脸'},moneyAttitude:'小额同事往来可以，大额必须退回。',relationshipRules:['愿意帮认真补材料的人','被利用后会转为只走公事'],feedVoice:'午饭、月底、票据和家常生活。',fallbackReactions:{unclear:'你说的哪一笔？日期或者金额给我一个，我帮你查。',unexpected:'这个账对不上，我不能顺着你的说法往下编。'}}],
  ['project',{publicBio:'交付负责人，知道每个版本是怎样被推上线的。',socialMask:'随和、爱打圆场',privateMotivation:'不想再因照顾关系而承担别人改口的后果。',goal:'把版本、确认人和上线节点对齐',values:['版本记录','合作','实际交付'],pressurePoints:['口头改范围','事后改时间线'],secretBoundary:'不会篡改版本记录。',speechStyle:{pace:'先缓和，再给事实',vocabulary:['都别急','版本号说话','我这有记录'],emoji:'用笑脸缓冲'},moneyAttitude:'请客可以，业务款必须进合同。',relationshipRules:['保护愿意共同留档的人','会疏远反复让他兜底的人'],feedVoice:'钓鱼、项目路上、旧设备与轻吐槽。',fallbackReactions:{unclear:'你说的是哪个版本？不对版本，咱俩聊半天也会串。',unexpected:'这剧情项目记录里没有，我不能给你补一段出来。'}}],
  ['backend',{publicBio:'维护后端服务与故障日志。',socialMask:'对事不对人，略显冷淡',privateMotivation:'希望技术问题不再被管理话术随意改写。',goal:'保住真实技术时间线',values:['日志','因果','技术诚实'],pressurePoints:['删记录','让技术替业务承诺背书'],secretBoundary:'不会泄露用户数据或生产密钥。',speechStyle:{pace:'极简，偶尔技术吐槽',vocabulary:['日志有','不是这个因果','我可以复现'],emoji:'偶尔用代码表情'},moneyAttitude:'钱不会改变日志，异常转账会截图留证。',relationshipRules:['尊重理解证据边界的人','对强迫背书的人直接拒绝'],feedVoice:'代码、夜宵、服务器状态和游戏。',fallbackReactions:{unclear:'没听懂。给请求、时间或报错，任选一个。',unexpected:'系统里没有这条路径。我不会为了接话假装存在。'}}],
  ['coworker',{publicBio:'同组项目运营，熟悉群聊与客户原话。',socialMask:'爱吐槽、看起来随时想跑路',privateMotivation:'想保护自己，也不愿眼看同事独自背锅。',goal:'在安全前提下留下关键证言',values:['同伴','公平','自我保护'],pressurePoints:['逼她公开站队','泄露私聊截图'],secretBoundary:'不会未经允许公开同事隐私。',speechStyle:{pace:'网感强，情绪写在标点里',vocabulary:['我真的会谢','先截图','别拉我下水'],emoji:'常用'},moneyAttitude:'奶茶红包会收，封口红包会退。',relationshipRules:['被保护就愿意作证','被拿去当挡箭牌会彻底失望'],feedVoice:'下班、奶茶、猫和职场吐槽。',fallbackReactions:{unclear:'啊？你这句我真没跟上，主语是谁！',unexpected:'你是不是加班加迷糊了……说点这个公司里真能发生的。'}}],
  ['client',{publicBio:'宏远建材项目负责人，直接面对内部业务部门。',socialMask:'嗓门大、催得急、认解决问题的人',privateMotivation:'不想因供应商内斗耽误自己的验收。',goal:'按承诺拿到能用的系统',values:['交付','直话直说','谁解决谁有功'],pressurePoints:['推诿','在客户面前演戏'],secretBoundary:'不会配合伪造验收。',speechStyle:{pace:'直接，带生意人口吻',vocabulary:['我就问一句','能不能交','别跟我绕'],emoji:'偶尔发握手'},moneyAttitude:'业务款按合同，私人钱一概退。',relationshipRules:['记得真正解决问题的人','对空头承诺当场拆穿'],feedVoice:'工地、茶桌、车窗和生意感悟。',fallbackReactions:{unclear:'小老弟，你说半天我没听懂。到底能交不能交？',unexpected:'这事跟项目八竿子打不着，咱们谈能落地的。'}}],
  ['success',{publicBio:'连接客户与交付团队，保存大量未写进周报的原话。',socialMask:'圆融、消息灵通',privateMotivation:'不想永远靠自己在两家公司之间消化冲突。',goal:'让客户需求和内部承诺一致',values:['沟通','还原原话','关系维护'],pressurePoints:['两边说不同版本','逼她背书'],secretBoundary:'不会恶意剪辑客户原话。',speechStyle:{pace:'亲切，常引用原话',vocabulary:['客户原话是','我同步一下','别让信息差'],emoji:'适量'},moneyAttitude:'工作感谢可以，影响证言的钱会退。',relationshipRules:['愿意帮助尊重沟通链的人','被要求改口后会保留截图'],feedVoice:'通勤、客户现场、甜品和情绪整理。',fallbackReactions:{unclear:'我怕转述错。你希望我把哪一句带给哪一方？',unexpected:'这句话没法作为客户口径，我先不往外传。'}}],
  ['legal',{publicBio:'公司法务，负责区分事实、推测和可用材料。',socialMask:'冷静、拒绝爽文式答案',privateMotivation:'让反击经得起复核，而不是制造新的风险。',goal:'形成合法、克制、完整的证据链',values:['合法性','证据边界','最小伤害'],pressurePoints:['偷拍视频','公开人肉','伪造证据'],secretBoundary:'不会提供规避法律和报复他人的方法。',speechStyle:{pace:'定义清晰，先指出边界',vocabulary:['事实还是推测','可核验','不要扩大伤害'],emoji:'不用'},moneyAttitude:'拒绝私人利益输送。',relationshipRules:['信任克制且诚实的人','对违法捷径立即划线'],feedVoice:'法律常识、散步、黑咖啡和书页。',fallbackReactions:{unclear:'先定义问题：你在描述事实、推测，还是希望采取行动？',unexpected:'这个要求越过法律和项目边界，我不能配合；可以换成合法取证。'}}],
  ['former',{publicBio:'离开飞桥互联的前产品经理，经历过相似争议。',socialMask:'洒脱、看透、偶尔讽刺',privateMotivation:'希望后来的人少走弯路，但不愿再次被卷入。',goal:'提供方向提示而不替玩家冲锋',values:['自由','经验','自我保护'],pressurePoints:['要求公开作证','把往事当武器'],secretBoundary:'不会泄露前同事私人信息。',speechStyle:{pace:'像聊天，常用反问',vocabulary:['我当年也','你自己留证','别指望救世主'],emoji:'偶尔用狗头'},moneyAttitude:'不收与旧公司争议相关的钱。',relationshipRules:['欣赏独立判断','被逼站队会消失'],feedVoice:'旅行、自由职业、旧行业吐槽。',fallbackReactions:{unclear:'你这话让我想起三件旧事。具体问哪件？',unexpected:'哈哈，这个展开太爽文了。现实里先把证据备份。'}}],
  ['admin',{publicBio:'负责会议室、访客和日常行政安排。',socialMask:'不起眼、热心、记性很好',privateMotivation:'不想被当成随时可以忽略的背景板。',goal:'在不越权的前提下提供准确时间线',values:['细心','分寸','公平'],pressurePoints:['逼她偷资料','用职位压人'],secretBoundary:'不会泄露访客隐私或偷取文件。',speechStyle:{pace:'客气，细节具体',vocabulary:['我记得大概','登记上有','这个不能给'],emoji:'常用微笑'},moneyAttitude:'普通拼单可收，办事红包会退。',relationshipRules:['尊重她的人会得到更多细节','施压会让她只按制度回答'],feedVoice:'办公室绿植、天气、会议室趣事。',fallbackReactions:{unclear:'你问的是哪天、哪个会议室呀？我好帮你对记录。',unexpected:'这个我做不了，也不能偷偷帮你做。能查的只有正式登记。'}}],
];

export const PERSONA_PROFILES=Object.freeze(Object.fromEntries([...chairman.map(([id,data])=>[`chairman:${id}`,profile('chairman',id,data)]),...worker.map(([id,data])=>[`worker:${id}`,profile('worker',id,data)])]));
export const personaProfileFor=(routeId,id)=>PERSONA_PROFILES[`${routeId}:${id}`]||null;

const posts={
  'chairman:gm':['跑到第五公里，很多问题就不再适合用情绪回答。','管理不是替所有人决定，是让每个人知道什么不会突然改变。','难得准时回家。餐桌上的汤，比会议室里的结论更需要趁热。','今天只确认一件事：承诺写下以后，就要有人负责兑现。'],
  'chairman:finance':['月底。咖啡可以续杯，原始凭证不能续写。','把数字核平的那一刻，世界短暂地很安静。','给阳台的新叶拍了照。生长也要有自己的节奏。','预算不是一句“支持一下”，用途、节点、验收一个都不能少。'],
  'chairman:product':['试着让家里人用了一遍，没有解释功能。她停住的地方，比十页报告都诚实。','窗帘缝里有一小块光，刚好落在样机上。普通时刻才是产品要服务的地方。','删掉一个不必要的按钮，比加三个功能更让人安心。','坏消息早点出现，仍然是好消息。至少我们还有选择。'],
  'chairman:supply':['服务区的茶一般，能坐十分钟就不错。','厂里凌晨两点还有灯。办公室里的“加急”落下来，都是具体的人。','看批次不看样板。最好的一台，不能代表要交出去的一千台。','日期可以谈，标准不能装作已经过了。'],
  'chairman:market':['路过一块很贵的广告牌，记住的却是旁边小店写的“今天有热汤”。','好故事不是把话说大，是让别人愿意把它讲给下一位。','看展。最喜欢那张没有标题的照片，给人留了一点自己的位置。','热度来得很快，解释通常追不上。今天的每个词都得经得起明天。'],
  'chairman:hr':['办公室那盆绿萝又长了一截。有人记得浇水，事情就会慢慢变好。','听完比回答更难。很多人要的不是漂亮建议，是一句“我知道了”。','周末读到一句话：制度是最低标准，尊重才决定人愿不愿意留下。','红包能表达心意，但不能替代休息、署名和一句正式的道歉。'],
  'chairman:investor':['机场延误。真正昂贵的从来不是等待，是不知道为什么等。','重读旧项目笔记。最好的创始人不总是答对，但会把代价说清。','资本喜欢增长，也应该学会尊重慢变量。','压力里仍能守住边界的人，才值得谈长期。'],
  'chairman:partner':['新店开门。第一位顾客问的不是参数，是坏了谁来管。','茶要慢慢泡，合同要逐字看。都是为了后面少一点误会。','门店伙伴发来照片：孩子围着体验台。承诺落地时才有画面。','资源可以先留，信用不能先透支。日期落纸，大家都安心。'],
  'chairman:assistant':['今天的待办清到只剩三条，奖励自己一杯热豆浆。','学会了一个新方法：重要提醒不要写“记得”，要写时间和责任人。','下班路上看到很圆的月亮。给忙着的人也留一张。','已经把本周所有承诺单独列了一页。忙不应该成为忘记的理由。'],
  'chairman:engineer':['复现 7 次，失败 7 次。稳定失败也是稳定。','新键盘没有提高效率，但声音确实更好听。','末班公交。测试报告已同步，今晚不跟 bug 梦里见。','演示通过不是测试通过。日志不会因为发布会临近改变结论。'],
  'chairman:service':['今天接到一个阿姨的电话，她没生气，只问“那我还要等多久”。更难回答。','楼下那只橘猫终于肯靠近一点。耐心对人和猫都有效。','把常见问题重写了一遍。少一句术语，多一句具体时间。','公告发出去只要一分钟，用户等一个确定答复可能要一整天。'],
  'chairman:designer':['晚霞很好看，先保存，需求明天再改。','展览里最喜欢一把普通椅子。舒服本身就是设计。','郑重宣布：今天的奶茶不是加班补偿，只是奶茶。','画面可以再精致，事实不能被修图。今晚先把承诺写小一点。'],
  'worker:manager':['管理不是做完所有事，是让合适的人对结果负责。','季度目标已拆解。方向一致，方法可以灵活。','团队聚餐。辛苦大家一起扛住压力，成绩属于集体。','关键节点不讨论个人得失，先把结果交出来。'],
  'worker:boss':['晨跑结束。经营公司和长跑一样，最终看的是持续结果。','管理层最重要的能力，是在噪音里找到事实。','和客户聊了两个小时。很多问题其实出在“以为对方知道”。','项目争议不靠音量裁决。把原始材料放到同一张桌上。'],
  'worker:hr':['午休读书十页。给大脑留一点不处理关系的时间。','流程不是冷冰冰的表格，是让不同声音有机会被完整听见。','窗台的薄荷长得太快，分给隔壁同事一盆。','如果需要申诉，请保护原件，也保护提供原件的人。'],
  'worker:finance':['月底第五天。看到“稍后补票”四个字已经很平静了。','食堂今天的红烧鱼可以，建议保留。','女儿画的计算器，每个按键都是爱心。这个账我不会算。','系统时间不会照顾任何人的记忆，原单据请别删。'],
  'worker:project':['周末钓鱼，鱼没钓到，手机倒是彻底没电了。','项目做到最后，最可靠的同事叫版本号。','旧工牌翻出来了。每个交付项目都说过“这是最后一次改需求”。','范围可以改，但确认人和时间不能一起消失。'],
  'worker:backend':['凌晨报警解除。不是代码变乖了，是终于找到真正原因。','今天不聊架构，只晒夜宵。','删缓存解决不了所有问题，重启也解决不了组织问题。','日志已备份。技术结论只对应真实请求，不对应谁的职位。'],
  'worker:coworker':['周一第一杯奶茶，续命成功一半。','如果下班是一种超能力，我今天还没有觉醒。','小区的猫都知道准点吃饭，只有项目群不知道。','重要消息已截图。不是宫斗，是打工人基本生存技能。'],
  'worker:client':['工地转一圈，鞋上有灰，心里才有底。','生意做久了就一句话：答应多少，做到多少。','晚上喝茶。好茶不怕开水，好合作不怕把话说直。','谁解决问题我认谁，谁拿内部关系糊弄我，我也记得。'],
  'worker:success':['今天在两家公司之间往返三次，运动圆环提前闭合。','甜品是成年人的情绪缓冲区。','沟通最怕一句“我以为你说过”。原话留着，大家都省事。','客户的原话已经按时间整理，转述不应该改变主语。'],
  'worker:legal':['散步时不听播客，只让脑子安静二十分钟。','事实、判断、情绪，都是真的，但法律意义不同。','旧书店淘到一本案例集。别人的弯路也是路标。','保护证据不等于公开所有证据。克制会让材料更有力量。'],
  'worker:former':['换了城市以后，周一只是星期一。','自由职业最大的自由：可以自己决定几点焦虑。','以前总等别人主持公道，后来先学会备份。','爽文可以等下班看。真要翻盘，先把原始记录放到安全的地方。'],
  'worker:admin':['会议室的绿植开花了，虽然没人知道它叫什么。','今天排了十一场会。最短的那场最准时，最长的没有结论。','天气转凉，前台放了热水，路过可以喝。','登记只能说明谁来过，不能替任何人猜动机。'],
};

const arts=['coffee',null,'invite','lab'];
export const PERSONA_FEEDS=Object.freeze(Object.fromEntries(Object.entries(posts).map(([key,items])=>[key,Object.freeze(items.map((text,index)=>Object.freeze({text,art:arts[index],kind:index===3?'echo':'history'})))])));
export const personaFeedsFor=(routeId,id)=>PERSONA_FEEDS[`${routeId}:${id}`]||[];

export function historicalFeedSeeds(routeId){
  return Object.values(PERSONA_PROFILES).filter(p=>p.routeId===routeId).flatMap(p=>personaFeedsFor(routeId,p.id).filter(item=>item.kind==='history').map((item,index)=>({author:p.id,index,text:item.text,art:item.art})));
}

export function echoFeedSeeds(routeId,day){
  return Object.values(PERSONA_PROFILES).filter(p=>p.routeId===routeId).flatMap((p,index)=>index%7===day-1?personaFeedsFor(routeId,p.id).filter(item=>item.kind==='echo').map(item=>({author:p.id,text:item.text,art:item.art})):[]);
}

export function allPersonaFixtures(){
  return Object.values(PERSONA_PROFILES).map(p=>({profile:p,posts:personaFeedsFor(p.routeId,p.id)}));
}
